# Video dataset CATER based on https://github.com/deepmind/multi_object_datasets .
_target_: ocl.datasets.WebdatasetDataModule
train_shards: "${oc.env:DATASET_PREFIX}/cater_with_masks/train/shard-{000000..000152}.tar"
train_size: 35427
val_shards: "${oc.env:DATASET_PREFIX}/cater_with_masks/val/shard-{000000..000016}.tar"
val_size: 3937
test_shards: "${oc.env:DATASET_PREFIX}/cater_with_masks/test/shard-{000000..000073}.tar"
test_size: 17100
