# Image dataset containing subsampled frames from CATER6 dataset.
# This dataset was constructed in order to mimic CLEVR6 as closely as possible, yet with higher
# complexity due to the change of camera perspective and potentially flying objects.
defaults:
  - cater6

# Values derived from running `bin/compute_dataset_size.py`.
train_size: 35304
val_size: 3933
# Test split is much larger than clevr6 due to the predefined splits of cater.
test_size: 17379

train_transforms:
  02_sample_frames:
    _target_: ocl.transforms.SampleSlices
    fields:
      - image
    n_slices_per_input: 3
    dim: 0
    seed: 457834752
    shuffle_buffer_size: 1000
eval_transforms:
  02_sample_frames:
    _target_: ocl.transforms.SampleSlices
    fields:
      - image
      - mask
      - camera_matrix
      - object_positions
    n_slices_per_input: 3
    dim: 0
    seed: 457834753
    shuffle_buffer_size: 1
