# @package _global_
# Evaluate center crop masks on COCO.

defaults:
  - /evaluation_config
  - /evaluation/projects/bridging/_base_metrics_vpt
  - /evaluation/projects/bridging/_preprocessing_coco
  - /evaluation/projects/bridging/_metrics_discovery_masks
  - /evaluation/projects/bridging/_metrics_discovery_bboxes
  - /dataset: coco2014_20k
  - _self_

eval_batch_size: 1

dataset:
  train_shards:
  test_shards:
